import type { NodeTypeDefinition } from '../types'

const triggerNodes: NodeTypeDefinition[] = [
  {
    type: 'business_manual_trigger',
    label: 'Manual Trigger',
    category: 'trigger',
    icon: '▶',
    color: '#f97316',
    bgColor: 'rgba(249,115,22,0.1)',
    description: 'Start business workflow manually.',
    inputs: 0,
    outputs: 1,
    tags: ['trigger', 'manual', 'business'],
    configFields: [],
  },
  {
    type: 'business_schedule_trigger',
    label: 'Schedule Trigger',
    category: 'trigger',
    icon: '⏰',
    color: '#f97316',
    bgColor: 'rgba(249,115,22,0.1)',
    description: 'Trigger business workflow by schedule.',
    inputs: 0,
    outputs: 1,
    tags: ['trigger', 'schedule', 'business'],
    configFields: [
      { name: 'cron', label: 'Cron Expression', type: 'text', defaultValue: '*/15 * * * *' },
      { name: 'timezone', label: 'Timezone', type: 'text', defaultValue: 'UTC' },
    ],
  },
]

const sourceNodes: NodeTypeDefinition[] = [
  {
    type: 'business_etl_source',
    label: 'ETL Output Source',
    category: 'source',
    icon: '🧩',
    color: '#3b82f6',
    bgColor: 'rgba(59,130,246,0.1)',
    description: 'Pull rows from latest successful ETL pipeline output.',
    inputs: 0,
    outputs: 1,
    tags: ['source', 'etl', 'pipeline'],
    configFields: [
      {
        name: 'pipeline_id',
        label: 'ETL Pipeline',
        type: 'select',
        required: true,
        description: 'Select ETL pipeline to read output rows.',
      },
      {
        name: 'pipeline_node_id',
        label: 'Pipeline Node (optional)',
        type: 'select',
        description: 'Pick specific ETL node output; leave empty for auto-detect.',
      },
    ],
  },
  {
    type: 'business_mlops_source',
    label: 'MLOps Output Source',
    category: 'source',
    icon: '🧠',
    color: '#3b82f6',
    bgColor: 'rgba(59,130,246,0.1)',
    description: 'Pull prediction/metrics rows from MLOps run output.',
    inputs: 0,
    outputs: 1,
    tags: ['source', 'mlops', 'prediction'],
    configFields: [
      {
        name: 'mlops_workflow_id',
        label: 'MLOps Workflow',
        type: 'select',
        required: true,
      },
      {
        name: 'mlops_run_id',
        label: 'MLOps Run (optional)',
        type: 'select',
      },
      {
        name: 'mlops_node_id',
        label: 'MLOps Node (optional)',
        type: 'select',
      },
    ],
  },
]

const transformNodes: NodeTypeDefinition[] = [
  {
    type: 'business_llm_prompt',
    label: 'Prompt Decision Model',
    category: 'transform',
    icon: '🤖',
    color: '#a855f7',
    bgColor: 'rgba(168,85,247,0.1)',
    description: 'Run prompt on local GPT-OSS20B (Ollama) or cloud model.',
    inputs: 1,
    outputs: 1,
    tags: ['llm', 'prompt', 'decision'],
    configFields: [
      {
        name: 'model',
        label: 'Model',
        type: 'select',
        required: true,
        defaultValue: 'gpt-oss20b',
      },
      {
        name: 'system_prompt',
        label: 'System Prompt',
        type: 'textarea',
        placeholder: 'You are a business workflow assistant...',
      },
      {
        name: 'strict_mode',
        label: 'Strict Output Mode',
        type: 'toggle',
        defaultValue: true,
        description: 'Enforce exact instruction-following and deterministic output when possible.',
      },
      {
        name: 'prompt',
        label: 'Prompt',
        type: 'textarea',
        required: true,
        placeholder: 'Based on input data, decide next action and provide recommended email draft.',
      },
      {
        name: 'output_format',
        label: 'Output Format',
        type: 'select',
        defaultValue: 'text',
        options: [
          { value: 'text', label: 'Text' },
          { value: 'html', label: 'HTML' },
          { value: 'code', label: 'Code' },
          { value: 'email', label: 'Email' },
        ],
        description: 'Select how response should be formatted and previewed.',
      },
      {
        name: 'include_sample_rows',
        label: 'Include Input Row Samples',
        type: 'toggle',
        defaultValue: true,
      },
      {
        name: 'sample_row_limit',
        label: 'Sample Row Count',
        type: 'number',
        defaultValue: 2,
      },
      {
        name: 'temperature',
        label: 'Temperature',
        type: 'number',
        defaultValue: 0.2,
      },
      {
        name: 'max_tokens',
        label: 'Max Tokens',
        type: 'number',
        defaultValue: 1024,
        description: 'Increase for longer/full outputs. Recommended: 1024-2048 for cloud models.',
      },
    ],
  },
  {
    type: 'business_analytics',
    label: 'Business Analytics',
    category: 'transform',
    icon: '📊',
    color: '#a855f7',
    bgColor: 'rgba(168,85,247,0.1)',
    description: 'Compute summary statistics for downstream business decisions.',
    inputs: 1,
    outputs: 1,
    tags: ['analytics', 'summary'],
    configFields: [],
  },
]

const destinationNodes: NodeTypeDefinition[] = [
  {
    type: 'business_mail_writer',
    label: 'Mail Writer',
    category: 'destination',
    icon: '✉️',
    color: '#22c55e',
    bgColor: 'rgba(34,197,94,0.1)',
    description: 'Create structured email output from workflow context.',
    inputs: 1,
    outputs: 0,
    tags: ['email', 'communication', 'destination'],
    configFields: [
      {
        name: 'to_email',
        label: 'To',
        type: 'text',
        defaultValue: 'team@example.com',
        description: 'Comma-separated recipients.',
      },
      {
        name: 'subject',
        label: 'Subject',
        type: 'text',
        defaultValue: 'Business Workflow Recommendation',
      },
      {
        name: 'body_template',
        label: 'Body Template (optional)',
        type: 'textarea',
        placeholder: 'If empty, upstream prompt output is used.',
      },
      {
        name: 'send_mode',
        label: 'Send Mode',
        type: 'select',
        defaultValue: 'send',
        options: [
          { value: 'send', label: 'Send Email' },
          { value: 'draft', label: 'Draft Only' },
        ],
        description: 'Send via SMTP or keep as draft.',
      },
      {
        name: 'include_dashboard_snapshot',
        label: 'Embed Dashboard Snapshot',
        type: 'toggle',
        defaultValue: false,
        description: 'Attach selected dashboard snapshot image in the email body.',
      },
      {
        name: 'dashboard_id',
        label: 'Dashboard For Snapshot',
        type: 'select',
        placeholder: 'Select dashboard',
      },
      {
        name: 'smtp_provider',
        label: 'SMTP Provider Preset',
        type: 'select',
        defaultValue: 'custom',
        options: [
          { value: 'gmail', label: 'Gmail' },
          { value: 'outlook', label: 'Outlook / Microsoft 365' },
          { value: 'custom', label: 'Custom' },
        ],
        description: 'Auto-fill SMTP host, port and security.',
      },
      {
        name: 'from_email',
        label: 'From Email',
        type: 'text',
        placeholder: 'Fallback env: BUSINESS_SMTP_FROM_EMAIL',
      },
      {
        name: 'smtp_host',
        label: 'SMTP Host',
        type: 'text',
        placeholder: 'Fallback env: BUSINESS_SMTP_HOST',
      },
      {
        name: 'smtp_port',
        label: 'SMTP Port',
        type: 'number',
        defaultValue: 587,
        description: 'Fallback env: BUSINESS_SMTP_PORT',
      },
      {
        name: 'smtp_security',
        label: 'SMTP Security',
        type: 'select',
        defaultValue: 'tls',
        options: [
          { value: 'tls', label: 'TLS (STARTTLS)' },
          { value: 'ssl', label: 'SSL' },
          { value: 'none', label: 'None' },
        ],
        description: 'Fallback env: BUSINESS_SMTP_SECURITY',
      },
      {
        name: 'smtp_username',
        label: 'SMTP Username',
        type: 'text',
        placeholder: 'Fallback env: BUSINESS_SMTP_USERNAME',
      },
      {
        name: 'smtp_password',
        label: 'SMTP Password',
        type: 'text',
        placeholder: 'Gmail: 16-char App Password (no spaces)',
        description: 'For Gmail use Google App Password, not your account password. Env fallback: BUSINESS_SMTP_PASSWORD',
      },
    ],
  },
  {
    type: 'business_whatsapp_sender',
    label: 'WhatsApp Sender',
    category: 'destination',
    icon: '💬',
    color: '#22c55e',
    bgColor: 'rgba(34,197,94,0.1)',
    description: 'Send WhatsApp template or text message via Meta Graph API.',
    inputs: 1,
    outputs: 0,
    tags: ['whatsapp', 'meta', 'communication', 'destination'],
    configFields: [
      {
        name: 'to_phone',
        label: 'To Phone Number',
        type: 'text',
        required: true,
        placeholder: 'E.164 format, e.g. 919876543210',
      },
      {
        name: 'send_mode',
        label: 'Send Mode',
        type: 'select',
        defaultValue: 'send',
        options: [
          { value: 'send', label: 'Send Message' },
          { value: 'draft', label: 'Draft Only' },
        ],
      },
      {
        name: 'message_type',
        label: 'Message Type',
        type: 'select',
        defaultValue: 'template',
        options: [
          { value: 'template', label: 'Template' },
          { value: 'text', label: 'Text' },
        ],
      },
      {
        name: 'template_name',
        label: 'Template Name',
        type: 'text',
        defaultValue: 'hello_world',
      },
      {
        name: 'template_language',
        label: 'Template Language Code',
        type: 'text',
        defaultValue: 'en_US',
      },
      {
        name: 'text_body',
        label: 'Text Body (optional)',
        type: 'textarea',
        placeholder: 'If empty, upstream prompt output is used for text messages.',
      },
      {
        name: 'request_payload_json',
        label: 'Request JSON Payload (optional)',
        type: 'textarea',
        placeholder: '{\n  \"messaging_product\": \"whatsapp\",\n  \"to\": \"{{to_phone}}\",\n  \"type\": \"template\",\n  \"template\": {\n    \"name\": \"hello_world\",\n    \"language\": { \"code\": \"en_US\" }\n  }\n}',
        description: 'If provided, this raw JSON is sent to Meta Graph API. Supports placeholders like {{to_phone}}, {{text_body}}, {{template_name}}, {{template_language}}, {{message_type}}, {{upstream_text}}.',
      },
      {
        name: 'preview_url',
        label: 'Preview URL (text messages)',
        type: 'toggle',
        defaultValue: false,
      },
      {
        name: 'api_version',
        label: 'Graph API Version',
        type: 'text',
        defaultValue: 'v25.0',
      },
      {
        name: 'phone_number_id',
        label: 'Phone Number ID',
        type: 'text',
        placeholder: 'Fallback env: BUSINESS_WHATSAPP_PHONE_NUMBER_ID',
      },
      {
        name: 'access_token',
        label: 'Access Token',
        type: 'password',
        placeholder: 'Fallback env: BUSINESS_WHATSAPP_ACCESS_TOKEN',
      },
    ],
  },
]

const flowNodes: NodeTypeDefinition[] = [
  {
    type: 'business_decision',
    label: 'Decision Gate',
    category: 'flow',
    icon: '⋄',
    color: 'var(--app-text-subtle)',
    bgColor: 'rgba(100,116,139,0.1)',
    description: 'Evaluate condition on LLM text or row field and branch/filter rows.',
    inputs: 1,
    outputs: 2,
    tags: ['decision', 'condition', 'branch'],
    configFields: [
      {
        name: 'field_name',
        label: 'Field Name (optional)',
        type: 'text',
        placeholder: 'Leave empty to evaluate on LLM response text',
      },
      {
        name: 'operator',
        label: 'Operator',
        type: 'select',
        defaultValue: 'contains',
        options: [
          { value: 'contains', label: 'Contains' },
          { value: 'equals', label: 'Equals' },
          { value: 'not_equals', label: 'Not Equals' },
          { value: 'starts_with', label: 'Starts With' },
          { value: 'ends_with', label: 'Ends With' },
          { value: 'gt', label: 'Greater Than' },
          { value: 'gte', label: 'Greater Than or Equal' },
          { value: 'lt', label: 'Less Than' },
          { value: 'lte', label: 'Less Than or Equal' },
          { value: 'regex', label: 'Regex' },
        ],
      },
      {
        name: 'compare_value',
        label: 'Compare Value',
        type: 'text',
        required: true,
      },
      {
        name: 'case_sensitive',
        label: 'Case Sensitive',
        type: 'toggle',
        defaultValue: false,
      },
      {
        name: 'true_mode',
        label: 'On True',
        type: 'select',
        defaultValue: 'filter_rows',
        options: [
          { value: 'filter_rows', label: 'Keep Matched Rows' },
          { value: 'emit_summary', label: 'Emit Decision Summary' },
        ],
      },
      {
        name: 'false_mode',
        label: 'On False',
        type: 'select',
        defaultValue: 'drop',
        options: [
          { value: 'drop', label: 'Drop Output' },
          { value: 'pass_through', label: 'Pass Through Input' },
          { value: 'emit_summary', label: 'Emit Decision Summary' },
        ],
      },
    ],
  },
  {
    type: 'business_merge',
    label: 'Merge',
    category: 'flow',
    icon: '⟨⟩',
    color: 'var(--app-text-subtle)',
    bgColor: 'rgba(100,116,139,0.1)',
    description: 'Merge all incoming rows from parallel branches.',
    inputs: 2,
    outputs: 1,
    tags: ['merge', 'flow'],
    configFields: [],
  },
]

export const ALL_BUSINESS_NODE_TYPES: NodeTypeDefinition[] = [
  ...triggerNodes,
  ...sourceNodes,
  ...transformNodes,
  ...destinationNodes,
  ...flowNodes,
]

export const BUSINESS_NODE_CATEGORIES = {
  trigger: { label: 'Triggers', color: '#f97316', icon: '▶' },
  source: { label: 'Sources', color: '#3b82f6', icon: '⬇' },
  transform: { label: 'AI & Analytics', color: '#a855f7', icon: '🤖' },
  destination: { label: 'Actions', color: '#22c55e', icon: '⬆' },
  flow: { label: 'Logic', color: 'var(--app-text-subtle)', icon: '⋄' },
}

export const getBusinessNodeDef = (type: string): NodeTypeDefinition | undefined =>
  ALL_BUSINESS_NODE_TYPES.find((n) => n.type === type)
