import type { NodeTypeDefinition } from '../types'

// ─── TRIGGERS ─────────────────────────────────────────────────────────────────

const triggerNodes: NodeTypeDefinition[] = [
  {
    type: 'manual_trigger',
    label: 'Manual Trigger',
    category: 'trigger',
    icon: '▶',
    color: '#f97316',
    bgColor: 'rgba(249,115,22,0.08)',
    description: 'Manually start pipeline execution',
    inputs: 0,
    outputs: 1,
    tags: ['trigger', 'manual'],
    configFields: [
      { name: 'execution_mode', label: 'Execution Mode', type: 'select', defaultValue: 'batch',
        options: [
          { value: 'batch', label: 'Batch Processing' },
          { value: 'incremental', label: 'Incremental Update' },
          { value: 'streaming', label: 'Streaming Incremental' },
        ] },
      { name: 'batch_size', label: 'Batch Size (rows/chunk)', type: 'number', defaultValue: 5000 },
      { name: 'incremental_field', label: 'Incremental Field (watermark)', type: 'text',
        placeholder: 'updated_at, id, timestamp' },
      { name: 'streaming_interval_seconds', label: 'Streaming Interval (seconds)', type: 'number', defaultValue: 5 },
      { name: 'streaming_max_batches', label: 'Streaming Max Batches', type: 'number', defaultValue: 10 },
    ],
  },
  {
    type: 'schedule_trigger',
    label: 'Schedule',
    category: 'trigger',
    icon: '⏰',
    color: '#f97316',
    bgColor: 'rgba(249,115,22,0.08)',
    description: 'Run pipeline on a cron schedule',
    inputs: 0,
    outputs: 1,
    tags: ['trigger', 'cron', 'schedule'],
    configFields: [
      { name: 'enabled', label: 'Enable Schedule', type: 'toggle', defaultValue: true,
        description: 'If disabled, this trigger will not schedule background execution.' },
      { name: 'schedule_preset', label: 'Schedule Pattern', type: 'select', defaultValue: 'hourly',
        options: [
          { value: 'every_1_min', label: 'Every 1 minute' },
          { value: 'every_5_min', label: 'Every 5 minutes' },
          { value: 'every_15_min', label: 'Every 15 minutes' },
          { value: 'hourly', label: 'Every hour' },
          { value: 'daily_9am', label: 'Daily at 9:00 AM' },
          { value: 'weekly_mon_9am', label: 'Weekly Monday 9:00 AM' },
          { value: 'custom', label: 'Custom Cron' },
        ] },
      { name: 'cron', label: 'Cron Expression', type: 'text', placeholder: '0 * * * *', defaultValue: '0 * * * *',
        description: 'Used when Schedule Pattern = Custom Cron.' },
      { name: 'timezone', label: 'Timezone', type: 'text', placeholder: 'UTC', defaultValue: 'UTC' },
      { name: 'execution_mode', label: 'Execution Mode', type: 'select', defaultValue: 'batch',
        options: [
          { value: 'batch', label: 'Batch Processing' },
          { value: 'incremental', label: 'Incremental Update' },
          { value: 'streaming', label: 'Streaming Incremental' },
        ] },
      { name: 'batch_size', label: 'Batch Size (rows/chunk)', type: 'number', defaultValue: 5000 },
      { name: 'incremental_field', label: 'Incremental Field (watermark)', type: 'text',
        placeholder: 'updated_at, id, timestamp' },
      { name: 'streaming_interval_seconds', label: 'Streaming Interval (seconds)', type: 'number', defaultValue: 5 },
      { name: 'streaming_max_batches', label: 'Streaming Max Batches', type: 'number', defaultValue: 10 },
    ],
  },
  {
    type: 'webhook_trigger',
    label: 'Webhook',
    category: 'trigger',
    icon: '🔗',
    color: '#f97316',
    bgColor: 'rgba(249,115,22,0.08)',
    description: 'Trigger pipeline via HTTP webhook',
    inputs: 0,
    outputs: 1,
    tags: ['trigger', 'webhook', 'http'],
    configFields: [
      { name: 'path', label: 'Webhook Path', type: 'text', placeholder: '/webhook/my-pipeline' },
      { name: 'method', label: 'HTTP Method', type: 'select',
        options: [{ value: 'POST', label: 'POST' }, { value: 'GET', label: 'GET' }], defaultValue: 'POST' },
      { name: 'auth_token', label: 'Auth Token', type: 'password', placeholder: 'Optional bearer token' },
      { name: 'execution_mode', label: 'Execution Mode', type: 'select', defaultValue: 'batch',
        options: [
          { value: 'batch', label: 'Batch Processing' },
          { value: 'incremental', label: 'Incremental Update' },
          { value: 'streaming', label: 'Streaming Incremental' },
        ] },
      { name: 'batch_size', label: 'Batch Size (rows/chunk)', type: 'number', defaultValue: 5000 },
      { name: 'incremental_field', label: 'Incremental Field (watermark)', type: 'text',
        placeholder: 'updated_at, id, timestamp' },
      { name: 'streaming_interval_seconds', label: 'Streaming Interval (seconds)', type: 'number', defaultValue: 5 },
      { name: 'streaming_max_batches', label: 'Streaming Max Batches', type: 'number', defaultValue: 10 },
    ],
  },
]

// ─── SOURCES ──────────────────────────────────────────────────────────────────

const sourceNodes: NodeTypeDefinition[] = [
  {
    type: 'workflow_input_source',
    label: 'Workflow Input',
    category: 'source',
    icon: '⤓',
    color: '#0891b2',
    bgColor: 'rgba(8,145,178,0.12)',
    description: 'Use input payload from parent Business Logic Workflow as source rows in child canvas.',
    inputs: 0,
    outputs: 1,
    tags: ['workflow', 'input', 'child-canvas', 'source'],
    configFields: [
      { name: 'sample_rows_limit', label: 'Sample Rows Limit (0 = unlimited)', type: 'number', defaultValue: 1000 },
    ],
  },
  {
    type: 'postgres_source',
    label: 'PostgreSQL',
    category: 'source',
    icon: '🐘',
    color: '#336791',
    bgColor: 'rgba(51,103,145,0.1)',
    description: 'Extract data from PostgreSQL database',
    inputs: 0,
    outputs: 1,
    tags: ['database', 'sql', 'postgres', 'structured'],
    configFields: [
      { name: 'host', label: 'Host', type: 'text', placeholder: 'localhost', required: true },
      { name: 'port', label: 'Port', type: 'number', defaultValue: 5432 },
      { name: 'database', label: 'Database', type: 'text', required: true },
      { name: 'user', label: 'Username', type: 'text', required: true },
      { name: 'password', label: 'Password', type: 'password' },
      { name: 'query', label: 'SQL Query', type: 'code', language: 'sql',
        placeholder: 'SELECT * FROM users LIMIT 1000', required: true },
    ],
  },
  {
    type: 'mysql_source',
    label: 'MySQL',
    category: 'source',
    icon: '🐬',
    color: '#4479a1',
    bgColor: 'rgba(68,121,161,0.1)',
    description: 'Extract data from MySQL database',
    inputs: 0,
    outputs: 1,
    tags: ['database', 'sql', 'mysql', 'structured'],
    configFields: [
      { name: 'host', label: 'Host', type: 'text', placeholder: 'localhost', required: true },
      { name: 'port', label: 'Port', type: 'number', defaultValue: 3306 },
      { name: 'database', label: 'Database', type: 'text', required: true },
      { name: 'user', label: 'Username', type: 'text', required: true },
      { name: 'password', label: 'Password', type: 'password' },
      { name: 'query', label: 'SQL Query', type: 'code', language: 'sql',
        placeholder: 'SELECT * FROM products', required: true },
    ],
  },
  {
    type: 'oracle_source',
    label: 'Oracle',
    category: 'source',
    icon: '🟠',
    color: '#f97316',
    bgColor: 'rgba(249,115,22,0.1)',
    description: 'Extract data from Oracle database',
    inputs: 0,
    outputs: 1,
    tags: ['database', 'sql', 'oracle', 'structured'],
    configFields: [
      { name: 'host', label: 'Host', type: 'text', placeholder: 'localhost', required: true },
      { name: 'port', label: 'Port', type: 'number', defaultValue: 1521 },
      { name: 'service_name', label: 'Service Name / Database', type: 'text', placeholder: 'ORCLCDB', defaultValue: 'ORCLCDB' },
      { name: 'sid', label: 'SID (optional)', type: 'text', placeholder: 'ORCL' },
      { name: 'dsn', label: 'DSN (optional override)', type: 'text', placeholder: 'localhost:1521/ORCLCDB' },
      { name: 'user', label: 'Username', type: 'text', required: true },
      { name: 'password', label: 'Password', type: 'password' },
      { name: 'query', label: 'SQL Query', type: 'code', language: 'sql',
        placeholder: 'SELECT * FROM YOUR_TABLE FETCH FIRST 1000 ROWS ONLY', required: true },
    ],
  },
  {
    type: 'mongodb_source',
    label: 'MongoDB',
    category: 'source',
    icon: '🍃',
    color: '#4db33d',
    bgColor: 'rgba(77,179,61,0.1)',
    description: 'Extract documents from MongoDB collection',
    inputs: 0,
    outputs: 1,
    tags: ['database', 'nosql', 'mongodb', 'semi-structured'],
    configFields: [
      { name: 'connection_string', label: 'Connection String', type: 'text',
        placeholder: 'mongodb://localhost:27017', required: true },
      { name: 'database', label: 'Database', type: 'text', required: true },
      { name: 'collection', label: 'Collection', type: 'text', required: true },
      { name: 'filter', label: 'Filter Query (JSON)', type: 'code', language: 'json',
        placeholder: '{}', defaultValue: '{}' },
      { name: 'limit', label: 'Limit', type: 'number', defaultValue: 1000 },
    ],
  },
  {
    type: 'redis_source',
    label: 'Redis',
    category: 'source',
    icon: '🔴',
    color: '#dc382d',
    bgColor: 'rgba(220,56,45,0.1)',
    description: 'Extract key-value data from Redis',
    inputs: 0,
    outputs: 1,
    tags: ['cache', 'nosql', 'redis', 'semi-structured'],
    configFields: [
      { name: 'host', label: 'Host', type: 'text', placeholder: 'localhost', required: true },
      { name: 'port', label: 'Port', type: 'number', defaultValue: 6379 },
      { name: 'password', label: 'Password', type: 'password' },
      { name: 'key_pattern', label: 'Key Pattern', type: 'text', placeholder: '*', defaultValue: '*' },
    ],
  },
  {
    type: 'elasticsearch_source',
    label: 'Elasticsearch',
    category: 'source',
    icon: '🔍',
    color: '#f5a623',
    bgColor: 'rgba(245,166,35,0.1)',
    description: 'Search and extract documents from Elasticsearch',
    inputs: 0,
    outputs: 1,
    tags: ['search', 'nosql', 'elasticsearch', 'unstructured'],
    configFields: [
      { name: 'hosts', label: 'Hosts (comma-separated)', type: 'text', placeholder: 'http://localhost:9200' },
      { name: 'index', label: 'Index', type: 'text', required: true },
      { name: 'query', label: 'Query (JSON)', type: 'code', language: 'json',
        placeholder: '{"query": {"match_all": {}}}', defaultValue: '{"query": {"match_all": {}}}' },
      { name: 'size', label: 'Page Size', type: 'number', defaultValue: 100 },
    ],
  },
  {
    type: 'csv_source',
    label: 'CSV File',
    category: 'source',
    icon: '📄',
    color: '#10b981',
    bgColor: 'rgba(16,185,129,0.1)',
    description: 'Read data from CSV file',
    inputs: 0,
    outputs: 1,
    tags: ['file', 'csv', 'structured'],
    configFields: [
      { name: 'file_path', label: 'File Path', type: 'text', placeholder: '/data/file.csv', required: true },
      { name: 'delimiter', label: 'Delimiter', type: 'text', defaultValue: ',' },
      { name: 'encoding', label: 'Encoding', type: 'select',
        options: [{value:'utf-8',label:'UTF-8'},{value:'latin-1',label:'Latin-1'},{value:'utf-16',label:'UTF-16'}],
        defaultValue: 'utf-8' },
      { name: 'has_header', label: 'Has Header Row', type: 'toggle', defaultValue: true },
    ],
  },
  {
    type: 'json_source',
    label: 'JSON File',
    category: 'source',
    icon: '{ }',
    color: '#6366f1',
    bgColor: 'rgba(99,102,241,0.1)',
    description: 'Read data from JSON file',
    inputs: 0,
    outputs: 1,
    tags: ['file', 'json', 'semi-structured'],
    configFields: [
      { name: 'file_path', label: 'File Path', type: 'text', placeholder: '/data/data.json', required: true },
      { name: 'json_path', label: 'JSON Path (root key)', type: 'text', placeholder: 'data.records' },
    ],
  },
  {
    type: 'excel_source',
    label: 'Excel File',
    category: 'source',
    icon: '📊',
    color: '#1d6f42',
    bgColor: 'rgba(29,111,66,0.1)',
    description: 'Read data from Excel spreadsheet (.xlsx, .xls)',
    inputs: 0,
    outputs: 1,
    tags: ['file', 'excel', 'structured'],
    configFields: [
      { name: 'file_path', label: 'File Path', type: 'text', placeholder: '/data/report.xlsx', required: true },
      { name: 'sheet', label: 'Sheet Name/Index', type: 'text', defaultValue: '0' },
      { name: 'has_header', label: 'Has Header Row', type: 'toggle', defaultValue: true },
    ],
  },
  {
    type: 'xml_source',
    label: 'XML File',
    category: 'source',
    icon: '🏷',
    color: '#f59e0b',
    bgColor: 'rgba(245,158,11,0.1)',
    description: 'Parse and extract data from XML files',
    inputs: 0,
    outputs: 1,
    tags: ['file', 'xml', 'semi-structured'],
    configFields: [
      { name: 'file_path', label: 'File Path', type: 'text', placeholder: '/data/feed.xml', required: true },
      { name: 'xpath', label: 'XPath Expression', type: 'text', placeholder: '//record' },
    ],
  },
  {
    type: 'parquet_source',
    label: 'Parquet File',
    category: 'source',
    icon: '📦',
    color: '#8b5cf6',
    bgColor: 'rgba(139,92,246,0.1)',
    description: 'Read columnar data from Parquet files',
    inputs: 0,
    outputs: 1,
    tags: ['file', 'parquet', 'structured', 'bigdata'],
    configFields: [
      { name: 'file_path', label: 'File Path / Glob', type: 'text', placeholder: '/data/*.parquet', required: true },
      { name: 'columns', label: 'Columns (comma-separated, empty=all)', type: 'text' },
    ],
  },
  {
    type: 'lmdb_source',
    label: 'LMDB',
    category: 'source',
    icon: '🗂',
    color: '#14b8a6',
    bgColor: 'rgba(20,184,166,0.1)',
    description: 'Read key-value records from LMDB environment',
    inputs: 0,
    outputs: 1,
    tags: ['lmdb', 'kv', 'profile', 'document'],
    configFields: [
      { name: 'env_path', label: 'LMDB Environment Path', type: 'text', placeholder: '/data/profile_store.lmdb', required: true },
      { name: 'db_name', label: 'Named DB (optional)', type: 'text', placeholder: 'profiles' },
      { name: 'key_prefix', label: 'Key Prefix', type: 'text', placeholder: 'pipeline:abc:' },
      { name: 'start_key', label: 'Start Key (optional)', type: 'text' },
      { name: 'end_key', label: 'End Key (optional)', type: 'text' },
      { name: 'key_contains', label: 'Key Contains Filter', type: 'text', placeholder: 'customer' },
      { name: 'value_contains', label: 'Value Contains Filter', type: 'text', placeholder: 'Bangalore' },
      {
        name: 'value_format',
        label: 'Value Decode Format',
        type: 'select',
        options: [
          { value: 'auto', label: 'Auto (JSON/Text/Base64)' },
          { value: 'json', label: 'JSON' },
          { value: 'text', label: 'Text (UTF-8)' },
          { value: 'base64', label: 'Base64' },
        ],
        defaultValue: 'auto',
      },
      { name: 'flatten_json_values', label: 'Flatten JSON Object Values', type: 'toggle', defaultValue: true },
      { name: 'expand_profile_documents', label: 'Expand Profile Documents', type: 'toggle', defaultValue: true },
      { name: 'include_entity_meta', label: 'Include Entity Meta', type: 'toggle', defaultValue: false },
      { name: 'limit', label: 'Read Limit (0 = all)', type: 'number', defaultValue: 1000 },
    ],
  },
  {
    type: 'rocksdb_source',
    label: 'RocksDB',
    category: 'source',
    icon: '🪨',
    color: '#0ea5e9',
    bgColor: 'rgba(14,165,233,0.12)',
    description: 'Read key-value records from RocksDB directory',
    inputs: 0,
    outputs: 1,
    tags: ['rocksdb', 'kv', 'profile', 'document'],
    configFields: [
      { name: 'env_path', label: 'RocksDB Path', type: 'text', placeholder: '/data/profile_store.rocksdb', required: true },
      { name: 'key_prefix', label: 'Key Prefix', type: 'text', placeholder: 'pipeline:abc:' },
      { name: 'start_key', label: 'Start Key (optional)', type: 'text' },
      { name: 'end_key', label: 'End Key (optional)', type: 'text' },
      { name: 'key_contains', label: 'Key Contains Filter', type: 'text', placeholder: 'customer' },
      { name: 'value_contains', label: 'Value Contains Filter', type: 'text', placeholder: 'Bangalore' },
      {
        name: 'value_format',
        label: 'Value Decode Format',
        type: 'select',
        options: [
          { value: 'auto', label: 'Auto (JSON/Text/Base64)' },
          { value: 'json', label: 'JSON' },
          { value: 'text', label: 'Text (UTF-8)' },
          { value: 'base64', label: 'Base64' },
        ],
        defaultValue: 'auto',
      },
      { name: 'flatten_json_values', label: 'Flatten JSON Object Values', type: 'toggle', defaultValue: true },
      { name: 'expand_profile_documents', label: 'Expand Profile Documents', type: 'toggle', defaultValue: true },
      { name: 'include_entity_meta', label: 'Include Entity Meta', type: 'toggle', defaultValue: false },
      { name: 'limit', label: 'Read Limit (0 = all)', type: 'number', defaultValue: 1000 },
    ],
  },
  {
    type: 'rest_api_source',
    label: 'REST API',
    category: 'source',
    icon: '🌐',
    color: '#06b6d4',
    bgColor: 'rgba(6,182,212,0.1)',
    description: 'Fetch data from REST API endpoint',
    inputs: 0,
    outputs: 1,
    tags: ['api', 'http', 'rest', 'semi-structured'],
    configFields: [
      { name: 'url', label: 'URL', type: 'text', placeholder: 'https://api.example.com/data', required: true },
      { name: 'method', label: 'Method', type: 'select',
        options: [{value:'GET',label:'GET'},{value:'POST',label:'POST'},{value:'PUT',label:'PUT'}], defaultValue: 'GET' },
      { name: 'headers', label: 'Headers (JSON)', type: 'code', language: 'json',
        placeholder: '{"Authorization": "Bearer token"}', defaultValue: '{}' },
      { name: 'params', label: 'Query Params (JSON)', type: 'code', language: 'json', defaultValue: '{}' },
      { name: 'body', label: 'Request Body (JSON)', type: 'code', language: 'json' },
      { name: 'json_path', label: 'JSON Path to Array', type: 'text', placeholder: 'data.items' },
      { name: 'pagination_enabled', label: 'Enable Pagination', type: 'toggle', defaultValue: false },
    ],
  },
  {
    type: 'graphql_source',
    label: 'GraphQL',
    category: 'source',
    icon: '◈',
    color: '#e535ab',
    bgColor: 'rgba(229,53,171,0.1)',
    description: 'Query data from GraphQL endpoint',
    inputs: 0,
    outputs: 1,
    tags: ['api', 'graphql', 'semi-structured'],
    configFields: [
      { name: 'endpoint', label: 'Endpoint URL', type: 'text', required: true },
      { name: 'query', label: 'GraphQL Query', type: 'code', language: 'graphql',
        placeholder: 'query { users { id name email } }', required: true },
      { name: 'variables', label: 'Variables (JSON)', type: 'code', language: 'json', defaultValue: '{}' },
      { name: 'headers', label: 'Headers (JSON)', type: 'code', language: 'json', defaultValue: '{}' },
    ],
  },
  {
    type: 's3_source',
    label: 'AWS S3',
    category: 'source',
    icon: '☁',
    color: '#ff9900',
    bgColor: 'rgba(255,153,0,0.1)',
    description: 'Read files from Amazon S3 bucket',
    inputs: 0,
    outputs: 1,
    tags: ['cloud', 's3', 'aws', 'file'],
    configFields: [
      { name: 'bucket', label: 'Bucket Name', type: 'text', required: true },
      { name: 'key', label: 'Object Key / Prefix', type: 'text', required: true },
      { name: 'access_key', label: 'Access Key ID', type: 'text' },
      { name: 'secret_key', label: 'Secret Access Key', type: 'password' },
      { name: 'region', label: 'Region', type: 'text', defaultValue: 'us-east-1' },
      { name: 'file_format', label: 'File Format', type: 'select',
        options: [{value:'csv',label:'CSV'},{value:'json',label:'JSON'},{value:'parquet',label:'Parquet'}] },
    ],
  },
  {
    type: 'kafka_source',
    label: 'Apache Kafka',
    category: 'source',
    icon: '🌊',
    color: '#231f20',
    bgColor: 'rgba(99,102,241,0.1)',
    description: 'Consume messages from Kafka topic',
    inputs: 0,
    outputs: 1,
    tags: ['streaming', 'kafka', 'queue', 'unstructured'],
    configFields: [
      { name: 'bootstrap_servers', label: 'Bootstrap Servers', type: 'text', placeholder: 'localhost:9092', required: true },
      { name: 'topic', label: 'Topic', type: 'text', required: true },
      { name: 'group_id', label: 'Consumer Group ID', type: 'text', defaultValue: 'etl-flow-consumer' },
      { name: 'max_records', label: 'Max Records', type: 'number', defaultValue: 1000 },
      { name: 'auto_offset_reset', label: 'Offset Reset', type: 'select',
        options: [{value:'earliest',label:'Earliest'},{value:'latest',label:'Latest'}], defaultValue: 'earliest' },
    ],
  },
]

// ─── TRANSFORMS ───────────────────────────────────────────────────────────────

const transformNodes: NodeTypeDefinition[] = [
  {
    type: 'profile_query_transform',
    label: 'Data Query',
    category: 'transform',
    icon: '⌕',
    color: '#a855f7',
    bgColor: 'rgba(168,85,247,0.1)',
    description: 'Filter records by field/path conditions and optionally project selected fields',
    inputs: 1,
    outputs: 1,
    tags: ['transform', 'query', 'filter', 'json', 'profile'],
    configFields: [
      { name: 'query_mode', label: 'Query Mode', type: 'select',
        options: [
          { value: 'upstream', label: 'Upstream (engine only)' },
          { value: 'pushdown', label: 'Pushdown (source-first)' },
          { value: 'hybrid', label: 'Hybrid (pushdown + engine refine)' },
        ],
        defaultValue: 'hybrid' },
      { name: 'field', label: 'Field / JSON Path', type: 'text', required: true, placeholder: 'workflowtracker.workflow[].workflow_id' },
      { name: 'operator', label: 'Operator', type: 'select',
        options: [
          { value: 'equals', label: 'Equals' },
          { value: 'not_equals', label: 'Not Equals' },
          { value: 'contains', label: 'Contains' },
          { value: 'not_contains', label: 'Not Contains' },
          { value: 'starts_with', label: 'Starts With' },
          { value: 'ends_with', label: 'Ends With' },
          { value: 'in', label: 'In (comma-separated values)' },
          { value: 'not_in', label: 'Not In (comma-separated values)' },
          { value: 'greater_than', label: 'Greater Than' },
          { value: 'greater_or_equal', label: 'Greater Or Equal' },
          { value: 'less_than', label: 'Less Than' },
          { value: 'less_or_equal', label: 'Less Or Equal' },
          { value: 'between', label: 'Between (min,max)' },
          { value: 'is_null', label: 'Is Null' },
          { value: 'is_not_null', label: 'Is Not Null' },
        ],
        defaultValue: 'equals' },
      { name: 'value', label: 'Value', type: 'text', placeholder: '504065711786070' },
      { name: 'criteria_mode', label: 'Criteria Mode', type: 'select',
        options: [
          { value: 'all', label: 'ALL conditions must match' },
          { value: 'any', label: 'ANY condition can match' },
        ],
        defaultValue: 'all' },
      { name: 'criteria', label: 'Advanced Criteria (JSON array, optional)', type: 'json', defaultValue: '[]' },
      { name: 'select_fields', label: 'Select Fields (comma/newline separated, optional)', type: 'textarea',
        placeholder: 'AGENTCODE\nworkflowtracker.workflow[].workflow_id\nworkflowtracker.workflow[].status' },
      { name: 'select_field_sorts', label: 'Per-Field Sort (JSON object)', type: 'json', defaultValue: '{}' },
      { name: 'select_field_aliases', label: 'Select Field Aliases (JSON object)', type: 'json', defaultValue: '{}' },
      { name: 'array_output_mode', label: 'Array Output', type: 'select',
        options: [
          { value: 'list', label: 'Keep as list' },
          { value: 'explode_rows', label: 'Explode into rows' },
        ],
        defaultValue: 'list' },
      { name: 'array_match_mode', label: 'Array Match Mode', type: 'select',
        options: [
          { value: 'all_elements', label: 'Keep all elements' },
          { value: 'matched_elements_only', label: 'Keep matched elements only' },
        ],
        defaultValue: 'all_elements' },
      { name: 'include_original_row', label: 'Include Original Row', type: 'toggle', defaultValue: true },
      { name: 'offset', label: 'Offset', type: 'number', defaultValue: 0 },
      { name: 'limit', label: 'Limit (0 = no limit)', type: 'number', defaultValue: 0 },
    ],
  },
  {
    type: 'filter_transform',
    label: 'Filter',
    category: 'transform',
    icon: '▽',
    color: '#a855f7',
    bgColor: 'rgba(168,85,247,0.1)',
    description: 'Filter rows based on conditions',
    inputs: 1,
    outputs: 1,
    tags: ['transform', 'filter', 'condition'],
    configFields: [
      { name: 'field', label: 'Field Name', type: 'text', required: true },
      { name: 'operator', label: 'Operator', type: 'select',
        options: [
          {value:'equals',label:'Equals'},{value:'not_equals',label:'Not Equals'},
          {value:'contains',label:'Contains'},{value:'not_contains',label:'Not Contains'},
          {value:'greater_than',label:'Greater Than'},{value:'less_than',label:'Less Than'},
          {value:'is_null',label:'Is Null'},{value:'is_not_null',label:'Is Not Null'},
        ], defaultValue: 'equals' },
      { name: 'value', label: 'Value', type: 'text' },
    ],
  },
  {
    type: 'map_transform',
    label: 'Custom Fields',
    category: 'transform',
    icon: '⊡',
    color: '#a855f7',
    bgColor: 'rgba(168,85,247,0.1)',
    description: 'Select fields or create advanced formula/JSON custom fields',
    inputs: 1,
    outputs: 1,
    tags: ['transform', 'select', 'map', 'fields', 'expression', 'json'],
    configFields: [
      { name: 'fields', label: 'Fields', type: 'text',
        placeholder: 'id, name, email, created_at', required: true },
      { name: 'sample_rows_limit', label: 'Sample Rows Limit (0 = unlimited)', type: 'number', defaultValue: 1000,
        description: 'Controls how many input/output sample rows are captured for previews and condition testing. Range: 0..100000.' },
    ],
  },
  {
    type: 'rename_transform',
    label: 'Rename Fields',
    category: 'transform',
    icon: '✎',
    color: '#a855f7',
    bgColor: 'rgba(168,85,247,0.1)',
    description: 'Rename column/field names',
    inputs: 1,
    outputs: 1,
    tags: ['transform', 'rename', 'fields'],
    configFields: [
      { name: 'mappings', label: 'Field Mappings (old_name: new_name, one per line)', type: 'textarea',
        placeholder: 'user_id: id\nfull_name: name\nemail_address: email' },
    ],
  },
  {
    type: 'aggregate_transform',
    label: 'Aggregate / Group By',
    category: 'transform',
    icon: 'Σ',
    color: '#a855f7',
    bgColor: 'rgba(168,85,247,0.1)',
    description: 'Aggregate data with GROUP BY operations',
    inputs: 1,
    outputs: 1,
    tags: ['transform', 'aggregate', 'groupby', 'sum', 'count'],
    configFields: [
      { name: 'group_by', label: 'Group By Fields (comma-separated)', type: 'text', required: true },
      { name: 'agg_field', label: 'Aggregate Field', type: 'text', required: true },
      { name: 'agg_func', label: 'Aggregate Function', type: 'select',
        options: [
          {value:'sum',label:'SUM'},{value:'count',label:'COUNT'},{value:'mean',label:'AVERAGE'},
          {value:'min',label:'MIN'},{value:'max',label:'MAX'},{value:'std',label:'STDEV'},
        ], defaultValue: 'sum' },
    ],
  },
  {
    type: 'join_transform',
    label: 'Join Two Sources',
    category: 'transform',
    icon: '⋈',
    color: '#a855f7',
    bgColor: 'rgba(168,85,247,0.1)',
    description: 'Join two different upstream sources by key columns',
    inputs: 2,
    outputs: 1,
    tags: ['transform', 'join', 'merge', 'lookup'],
    configFields: [
      { name: 'left_source_node', label: 'Left Source Node', type: 'select' },
      { name: 'right_source_node', label: 'Right Source Node', type: 'select' },
      { name: 'left_key', label: 'Left Join Key', type: 'text', placeholder: 'id', required: true },
      { name: 'right_key', label: 'Right Join Key', type: 'text', placeholder: 'id', required: true },
      { name: 'join_type', label: 'Join Type', type: 'select',
        options: [
          { value: 'inner', label: 'Inner Join' },
          { value: 'left', label: 'Left Join' },
          { value: 'right', label: 'Right Join' },
          { value: 'full', label: 'Full Outer Join' },
        ],
        defaultValue: 'inner' },
      { name: 'left_suffix', label: 'Left Suffix', type: 'text', defaultValue: '_left' },
      { name: 'right_suffix', label: 'Right Suffix', type: 'text', defaultValue: '_right' },
    ],
  },
  {
    type: 'sort_transform',
    label: 'Sort',
    category: 'transform',
    icon: '↕',
    color: '#a855f7',
    bgColor: 'rgba(168,85,247,0.1)',
    description: 'Sort rows by field values',
    inputs: 1,
    outputs: 1,
    tags: ['transform', 'sort', 'order'],
    configFields: [
      { name: 'field', label: 'Sort Field', type: 'text', required: true },
      { name: 'order', label: 'Order', type: 'select',
        options: [{value:'asc',label:'Ascending ↑'},{value:'desc',label:'Descending ↓'}],
        defaultValue: 'asc' },
    ],
  },
  {
    type: 'deduplicate_transform',
    label: 'Deduplicate',
    category: 'transform',
    icon: '⊘',
    color: '#a855f7',
    bgColor: 'rgba(168,85,247,0.1)',
    description: 'Remove duplicate rows',
    inputs: 1,
    outputs: 1,
    tags: ['transform', 'deduplicate', 'unique'],
    configFields: [
      { name: 'key_field', label: 'Key Field (empty = all fields)', type: 'text',
        placeholder: 'id' },
      { name: 'keep', label: 'Keep', type: 'select',
        options: [{value:'first',label:'First occurrence'},{value:'last',label:'Last occurrence'}],
        defaultValue: 'first' },
    ],
  },
  {
    type: 'delay_transform',
    label: 'Delay',
    category: 'transform',
    icon: '🕒',
    color: '#a855f7',
    bgColor: 'rgba(168,85,247,0.1)',
    description: 'Delay pass-through messages by configured duration',
    inputs: 1,
    outputs: 1,
    tags: ['transform', 'delay', 'wait', 'passthrough'],
    configFields: [
      { name: 'delay_value', label: 'Delay Value', type: 'number', defaultValue: 1 },
      { name: 'delay_unit', label: 'Delay Unit', type: 'select', defaultValue: 's',
        options: [
          { value: 'us', label: 'Microseconds (us)' },
          { value: 'ms', label: 'Milliseconds (ms)' },
          { value: 's', label: 'Seconds (s)' },
          { value: 'm', label: 'Minutes (m)' },
          { value: 'h', label: 'Hours (h)' },
          { value: 'd', label: 'Days (d)' },
        ] },
      { name: 'delay_scope', label: 'Delay Scope', type: 'select', defaultValue: 'batch',
        options: [
          { value: 'batch', label: 'Once Per Batch' },
          { value: 'message', label: 'Each Message' },
        ] },
      { name: 'downstream_invoke_mode', label: 'Downstream Invoke Mode', type: 'select', defaultValue: 'row_by_row',
        options: [
          { value: 'row_by_row', label: 'Per Message (fan-out)' },
          { value: 'batch', label: 'Batch (single call)' },
        ] },
      { name: 'passthrough_on_receive', label: 'Passthrough On Receive', type: 'toggle', defaultValue: false },
    ],
  },
  {
    type: 'cursor_processor_transform',
    label: 'Cursor Processor',
    category: 'transform',
    icon: '⟢',
    color: '#a855f7',
    bgColor: 'rgba(168,85,247,0.1)',
    description: 'Cursor-aware stream processing (checkpoint, out-of-order, dedupe)',
    inputs: 1,
    outputs: 1,
    tags: ['transform', 'cursor', 'streaming', 'kafka', 'checkpoint', 'compliance'],
    configFields: [
      { name: 'processing_mode', label: 'Processing Mode', type: 'select',
        options: [{ value: 'batch', label: 'Batch' }, { value: 'row_by_row', label: 'Row by Row' }],
        defaultValue: 'batch' },
      { name: 'downstream_invoke_mode', label: 'Downstream Invoke Mode', type: 'select',
        options: [{ value: 'batch', label: 'Batch (single call)' }, { value: 'row_by_row', label: 'Per Row (fan-out)' }],
        defaultValue: 'batch' },
      { name: 'cursor_field', label: 'Cursor Field', type: 'text', required: true, placeholder: 'MIS_TXNDATE / offset / event_time' },
      { name: 'dedupe_field', label: 'Dedupe Key Field (optional)', type: 'text', placeholder: 'TRANSACTIONID / message_id' },
      { name: 'on_duplicate', label: 'On Duplicate Key+Cursor', type: 'select',
        options: [{ value: 'drop', label: 'Drop' }, { value: 'keep', label: 'Keep' }],
        defaultValue: 'drop' },
      { name: 'enforce_monotonic', label: 'Enforce Monotonic Cursor', type: 'toggle', defaultValue: true },
      { name: 'allow_equal_cursor', label: 'Allow Equal Cursor', type: 'toggle', defaultValue: false },
      { name: 'allowed_lateness', label: 'Allowed Lateness', type: 'text', defaultValue: '0s', placeholder: '0s, 30s, 5m, 2h, 1d' },
      { name: 'on_late', label: 'On Late Event', type: 'select',
        options: [{ value: 'drop', label: 'Drop' }, { value: 'keep', label: 'Keep' }, { value: 'tag', label: 'Tag and Keep' }],
        defaultValue: 'drop' },
      { name: 'on_missing_cursor', label: 'On Missing Cursor', type: 'select',
        options: [{ value: 'keep', label: 'Keep' }, { value: 'drop', label: 'Drop' }, { value: 'tag', label: 'Tag and Keep' }],
        defaultValue: 'keep' },
      { name: 'status_field', label: 'Status Field Name', type: 'text', defaultValue: '_cursor_status' },
      { name: 'dedupe_cache_size', label: 'Dedupe Cache Size', type: 'number', defaultValue: 10000 },
      { name: 'sample_rows_limit', label: 'Sample Rows Limit (0 = unlimited)', type: 'number', defaultValue: 1000,
        description: 'Controls how many input/output sample rows are captured for previews and condition testing. Range: 0..100000.' },
    ],
  },
  {
    type: 'type_convert_transform',
    label: 'Type Conversion',
    category: 'transform',
    icon: '⇄',
    color: '#a855f7',
    bgColor: 'rgba(168,85,247,0.1)',
    description: 'Convert field data types',
    inputs: 1,
    outputs: 1,
    tags: ['transform', 'type', 'convert', 'cast'],
    configFields: [
      { name: 'field', label: 'Field Name', type: 'text', required: true },
      { name: 'target_type', label: 'Target Type', type: 'select',
        options: [
          {value:'string',label:'String'},{value:'integer',label:'Integer'},
          {value:'float',label:'Float'},{value:'boolean',label:'Boolean'},
          {value:'date',label:'Date'},{value:'datetime',label:'DateTime'},
        ], defaultValue: 'string' },
      { name: 'format', label: 'Date Format (if date)', type: 'text', placeholder: '%Y-%m-%d' },
    ],
  },
  {
    type: 'python_script_transform',
    label: 'Python Script',
    category: 'transform',
    icon: '🐍',
    color: '#3b82f6',
    bgColor: 'rgba(59,130,246,0.1)',
    description: 'Transform data with custom Python code',
    inputs: 1,
    outputs: 1,
    tags: ['transform', 'python', 'script', 'custom'],
    configFields: [
      { name: 'script', label: 'Python Script', type: 'code', language: 'python', required: true,
        defaultValue: '# input_data: List[dict] — your rows\n# Assign results to `output`\n\noutput = []\nfor row in input_data:\n    # Modify, filter or enrich rows here\n    output.append(row)\n' },
    ],
  },
  {
    type: 'sql_transform',
    label: 'SQL Transform',
    category: 'transform',
    icon: '🗄',
    color: '#a855f7',
    bgColor: 'rgba(168,85,247,0.1)',
    description: 'Transform data using SQL queries (in-memory)',
    inputs: 1,
    outputs: 1,
    tags: ['transform', 'sql', 'query'],
    configFields: [
      { name: 'query', label: 'SQL Query', type: 'code', language: 'sql', required: true,
        defaultValue: 'SELECT * FROM df WHERE 1=1' },
    ],
  },
  {
    type: 'limit_transform',
    label: 'Limit Rows',
    category: 'transform',
    icon: '#',
    color: '#a855f7',
    bgColor: 'rgba(168,85,247,0.1)',
    description: 'Limit number of rows in output',
    inputs: 1,
    outputs: 1,
    tags: ['transform', 'limit', 'sample'],
    configFields: [
      { name: 'limit', label: 'Max Rows', type: 'number', defaultValue: 100, required: true },
    ],
  },
  {
    type: 'flatten_transform',
    label: 'Flatten JSON',
    category: 'transform',
    icon: '⟤',
    color: '#a855f7',
    bgColor: 'rgba(168,85,247,0.1)',
    description: 'Flatten nested JSON objects',
    inputs: 1,
    outputs: 1,
    tags: ['transform', 'flatten', 'json', 'nested'],
    configFields: [
      { name: 'separator', label: 'Key Separator', type: 'text', defaultValue: '_' },
    ],
  },
  {
    type: 'business_workflow',
    label: 'Business Logic Workflow',
    category: 'transform',
    icon: '🧭',
    color: '#a855f7',
    bgColor: 'rgba(168,85,247,0.1)',
    description: 'Run a child business workflow canvas from incoming rows.',
    inputs: 1,
    outputs: 1,
    tags: ['business', 'workflow', 'child-canvas', 'row-level'],
    configFields: [
      { name: 'workflow_id', label: 'Workflow', type: 'select', required: false, options: [] },
      { name: 'invoke_mode', label: 'Invoke Mode', type: 'select', defaultValue: 'once_per_batch',
        options: [
          { value: 'once_per_batch', label: 'Once Per Batch' },
          { value: 'per_row', label: 'Per Row (Instance Per Record)' },
        ] },
      { name: 'max_instances', label: 'Max Instances Per Execution', type: 'number', defaultValue: 10000,
        description: 'Safety cap for run creation in one pipeline execution (1..100000).' },
      { name: 'wait_for_completion', label: 'Wait For Completion', type: 'toggle', defaultValue: false },
      { name: 'completion_timeout_seconds', label: 'Completion Timeout (seconds)', type: 'number', defaultValue: 90 },
      { name: 'include_input_payload', label: 'Pass Input Payload To Workflow', type: 'toggle', defaultValue: true },
      { name: 'custom_variables_json', label: 'Custom Variables (JSON)', type: 'code', language: 'json', defaultValue: '{}' },
      { name: 'profile_store', label: 'Profile Store Hint', type: 'select', defaultValue: 'sqlite',
        options: [
          { value: 'sqlite', label: 'SQLite' },
          { value: 'lmdb', label: 'LMDB' },
          { value: 'rocksdb', label: 'RocksDB' },
          { value: 'redis', label: 'Redis' },
          { value: 'oracle', label: 'Oracle' },
        ] },
      { name: 'profile_namespace', label: 'Profile Namespace', type: 'text', placeholder: 'agent_profile_v1' },
    ],
  },
  {
    type: 'business_analytics',
    label: 'Business Analytics',
    category: 'transform',
    icon: '📊',
    color: '#a855f7',
    bgColor: 'rgba(168,85,247,0.1)',
    description: 'Compute business-style summary metrics from incoming rows',
    inputs: 1,
    outputs: 1,
    tags: ['analytics', 'summary', 'business'],
    configFields: [],
  },
]

// ─── DESTINATIONS ─────────────────────────────────────────────────────────────

const destinationNodes: NodeTypeDefinition[] = [
  {
    type: 'postgres_destination',
    label: 'PostgreSQL',
    category: 'destination',
    icon: '🐘',
    color: '#22c55e',
    bgColor: 'rgba(34,197,94,0.1)',
    description: 'Load data into PostgreSQL table',
    inputs: 1,
    outputs: 0,
    tags: ['database', 'sql', 'postgres', 'load'],
    configFields: [
      { name: 'host', label: 'Host', type: 'text', placeholder: 'localhost', required: true },
      { name: 'port', label: 'Port', type: 'number', defaultValue: 5432 },
      { name: 'database', label: 'Database', type: 'text', required: true },
      { name: 'user', label: 'Username', type: 'text', required: true },
      { name: 'password', label: 'Password', type: 'password' },
      { name: 'table', label: 'Target Table', type: 'text', required: true },
      { name: 'if_exists', label: 'If Table Exists', type: 'select',
        options: [{value:'append',label:'Append'},{value:'replace',label:'Replace'},{value:'fail',label:'Fail'}],
        defaultValue: 'append' },
    ],
  },
  {
    type: 'mongodb_destination',
    label: 'MongoDB',
    category: 'destination',
    icon: '🍃',
    color: '#22c55e',
    bgColor: 'rgba(34,197,94,0.1)',
    description: 'Insert documents into MongoDB collection',
    inputs: 1,
    outputs: 0,
    tags: ['database', 'nosql', 'mongodb', 'load'],
    configFields: [
      { name: 'connection_string', label: 'Connection String', type: 'text', required: true },
      { name: 'database', label: 'Database', type: 'text', required: true },
      { name: 'collection', label: 'Collection', type: 'text', required: true },
      { name: 'write_mode', label: 'Write Mode', type: 'select',
        options: [{value:'insert',label:'Insert'},{value:'upsert',label:'Upsert'},{value:'replace',label:'Replace'}],
        defaultValue: 'insert' },
    ],
  },
  {
    type: 'oracle_destination',
    label: 'Oracle',
    category: 'destination',
    icon: '🟠',
    color: '#22c55e',
    bgColor: 'rgba(34,197,94,0.1)',
    description: 'Load data into Oracle table',
    inputs: 1,
    outputs: 0,
    tags: ['database', 'sql', 'oracle', 'load'],
    configFields: [
      { name: 'host', label: 'Host', type: 'text', placeholder: 'localhost', required: true },
      { name: 'port', label: 'Port', type: 'number', defaultValue: 1521 },
      { name: 'service_name', label: 'Service Name / Database', type: 'text', placeholder: 'ORCLCDB', defaultValue: 'ORCLCDB' },
      { name: 'sid', label: 'SID (optional)', type: 'text', placeholder: 'ORCL' },
      { name: 'dsn', label: 'DSN (optional override)', type: 'text', placeholder: 'localhost:1521/ORCLCDB' },
      { name: 'user', label: 'Username', type: 'text', required: true },
      { name: 'password', label: 'Password', type: 'password' },
      { name: 'schema', label: 'Schema (optional)', type: 'text', placeholder: 'SYSTEM' },
      { name: 'table', label: 'Target Table', type: 'text', required: true },
      { name: 'if_exists', label: 'If Table Exists', type: 'select',
        options: [{ value: 'append', label: 'Append' }, { value: 'replace', label: 'Replace' }, { value: 'fail', label: 'Fail' }],
        defaultValue: 'append' },
    ],
  },
  {
    type: 'csv_destination',
    label: 'CSV File',
    category: 'destination',
    icon: '📄',
    color: '#22c55e',
    bgColor: 'rgba(34,197,94,0.1)',
    description: 'Write data to CSV file',
    inputs: 1,
    outputs: 0,
    tags: ['file', 'csv', 'export', 'load'],
    configFields: [
      { name: 'file_path', label: 'Output File Path', type: 'text', required: true },
      { name: 'delimiter', label: 'Delimiter', type: 'text', defaultValue: ',' },
      { name: 'include_header', label: 'Include Header', type: 'toggle', defaultValue: true },
      { name: 'encoding', label: 'Encoding', type: 'text', defaultValue: 'utf-8' },
      { name: 'write_mode', label: 'Write Mode', type: 'select',
        options: [{ value: 'replace', label: 'Replace File' }, { value: 'append', label: 'Append File' }],
        defaultValue: 'replace' },
      { name: 'flush_mode', label: 'Flush Mode', type: 'select',
        options: [{ value: 'batch', label: 'Batch Write' }, { value: 'row', label: 'Row by Row' }],
        defaultValue: 'batch' },
    ],
  },
  {
    type: 'json_destination',
    label: 'JSON File',
    category: 'destination',
    icon: '{ }',
    color: '#22c55e',
    bgColor: 'rgba(34,197,94,0.1)',
    description: 'Write data to JSON file',
    inputs: 1,
    outputs: 0,
    tags: ['file', 'json', 'export', 'load'],
    configFields: [
      { name: 'file_path', label: 'Output File Path', type: 'text', required: true },
      { name: 'indent', label: 'JSON Indent', type: 'number', defaultValue: 2 },
      { name: 'orient', label: 'Orientation', type: 'select',
        options: [{value:'records',label:'Records [{...}]'},{value:'values',label:'Values [[...]]'}],
        defaultValue: 'records' },
      { name: 'date_format', label: 'Date Format', type: 'select',
        options: [{ value: 'iso', label: 'ISO (readable)' }, { value: 'epoch', label: 'Epoch' }],
        defaultValue: 'iso' },
      { name: 'date_unit', label: 'Epoch Unit', type: 'select',
        options: [{ value: 'ms', label: 'Milliseconds' }, { value: 's', label: 'Seconds' }, { value: 'us', label: 'Microseconds' }, { value: 'ns', label: 'Nanoseconds' }],
        defaultValue: 'ms' },
      { name: 'date_only_midnight', label: 'Date-Only for Midnight', type: 'toggle', defaultValue: true },
      { name: 'datetime_output_pattern', label: 'Datetime Pattern', type: 'text', defaultValue: '%Y-%d-%m %H:%M:%S' },
    ],
  },
  {
    type: 's3_destination',
    label: 'AWS S3',
    category: 'destination',
    icon: '☁',
    color: '#22c55e',
    bgColor: 'rgba(34,197,94,0.1)',
    description: 'Upload data files to Amazon S3',
    inputs: 1,
    outputs: 0,
    tags: ['cloud', 's3', 'aws', 'load'],
    configFields: [
      { name: 'bucket', label: 'Bucket Name', type: 'text', required: true },
      { name: 'key', label: 'Object Key / Path', type: 'text', required: true },
      { name: 'access_key', label: 'Access Key ID', type: 'text' },
      { name: 'secret_key', label: 'Secret Access Key', type: 'password' },
      { name: 'region', label: 'Region', type: 'text', defaultValue: 'us-east-1' },
      { name: 'format', label: 'Format', type: 'select',
        options: [{value:'csv',label:'CSV'},{value:'json',label:'JSON'},{value:'parquet',label:'Parquet'}] },
    ],
  },
  {
    type: 'elasticsearch_destination',
    label: 'Elasticsearch',
    category: 'destination',
    icon: '🔍',
    color: '#22c55e',
    bgColor: 'rgba(34,197,94,0.1)',
    description: 'Index documents into Elasticsearch',
    inputs: 1,
    outputs: 0,
    tags: ['search', 'elasticsearch', 'load'],
    configFields: [
      { name: 'hosts', label: 'Hosts', type: 'text', placeholder: 'http://localhost:9200' },
      { name: 'index', label: 'Index Name', type: 'text', required: true },
      { name: 'id_field', label: 'Document ID Field', type: 'text' },
    ],
  },
  {
    type: 'rest_api_destination',
    label: 'REST API',
    category: 'destination',
    icon: '🌐',
    color: '#22c55e',
    bgColor: 'rgba(34,197,94,0.1)',
    description: 'POST data to a REST API endpoint',
    inputs: 1,
    outputs: 0,
    tags: ['api', 'http', 'rest', 'webhook', 'load'],
    configFields: [
      { name: 'url', label: 'URL', type: 'text', required: true },
      { name: 'method', label: 'Method', type: 'select',
        options: [{value:'POST',label:'POST'},{value:'PUT',label:'PUT'},{value:'PATCH',label:'PATCH'}],
        defaultValue: 'POST' },
      { name: 'headers', label: 'Headers (JSON)', type: 'code', language: 'json', defaultValue: '{}' },
      { name: 'batch_size', label: 'Batch Size (rows per request)', type: 'number', defaultValue: 100 },
    ],
  },
  {
    type: 'business_mail_writer',
    label: 'Mail Writer',
    category: 'destination',
    icon: '📧',
    color: '#f59e0b',
    bgColor: 'rgba(245,158,11,0.14)',
    description: 'Create and optionally send email from incoming pipeline context',
    inputs: 1,
    outputs: 0,
    tags: ['action', 'email', 'business'],
    configFields: [
      { name: 'to_email', label: 'To', type: 'text', required: true, placeholder: 'team@example.com' },
      { name: 'subject', label: 'Subject', type: 'text', defaultValue: 'Business workflow recommendation' },
      { name: 'body_template', label: 'Body Template (optional)', type: 'textarea', placeholder: 'If empty, upstream row context is used.' },
      { name: 'invoke_mode', label: 'Invoke Mode', type: 'select',
        options: [{ value: 'once_per_batch', label: 'Once Per Batch (Fast)' }, { value: 'per_row', label: 'Per Row' }],
        defaultValue: 'once_per_batch',
        description: 'Use per-row only when you need one mail per row; once-per-batch is much faster.' },
      { name: 'send_mode', label: 'Send Mode', type: 'select',
        options: [{ value: 'send', label: 'Send Email' }, { value: 'draft', label: 'Draft Only' }],
        defaultValue: 'draft' },
      { name: 'from_email', label: 'From Email', type: 'text', placeholder: 'Fallback env: BUSINESS_SMTP_FROM_EMAIL' },
      { name: 'smtp_host', label: 'SMTP Host', type: 'text', placeholder: 'Fallback env: BUSINESS_SMTP_HOST' },
      { name: 'smtp_port', label: 'SMTP Port', type: 'number', defaultValue: 587 },
      { name: 'smtp_security', label: 'SMTP Security', type: 'select',
        options: [{ value: 'tls', label: 'TLS (STARTTLS)' }, { value: 'ssl', label: 'SSL' }, { value: 'none', label: 'None' }],
        defaultValue: 'tls' },
      { name: 'smtp_username', label: 'SMTP Username', type: 'text', placeholder: 'Fallback env: BUSINESS_SMTP_USERNAME' },
      { name: 'smtp_password', label: 'SMTP Password', type: 'password', placeholder: 'Fallback env: BUSINESS_SMTP_PASSWORD' },
    ],
  },
  {
    type: 'business_whatsapp_sender',
    label: 'WhatsApp Sender',
    category: 'destination',
    icon: '💬',
    color: '#10b981',
    bgColor: 'rgba(16,185,129,0.14)',
    description: 'Send WhatsApp template or text message via Meta Graph API',
    inputs: 1,
    outputs: 0,
    tags: ['action', 'whatsapp', 'meta', 'business'],
    configFields: [
      { name: 'to_phone', label: 'To Phone Number', type: 'text', required: true, placeholder: 'E.164 e.g. 919876543210' },
      { name: 'send_mode', label: 'Send Mode', type: 'select',
        options: [{ value: 'send', label: 'Send Message' }, { value: 'draft', label: 'Draft Only' }],
        defaultValue: 'draft' },
      { name: 'message_type', label: 'Message Type', type: 'select',
        options: [{ value: 'template', label: 'Template' }, { value: 'text', label: 'Text' }],
        defaultValue: 'template' },
      { name: 'template_name', label: 'Template Name', type: 'text', defaultValue: 'hello_world' },
      { name: 'template_language', label: 'Template Language Code', type: 'text', defaultValue: 'en_US' },
      { name: 'text_body', label: 'Text Body (optional)', type: 'textarea', placeholder: 'If empty, upstream context is used.' },
      { name: 'request_payload_json', label: 'Request JSON Payload (optional)', type: 'code', language: 'json', placeholder: '{\"messaging_product\":\"whatsapp\",\"to\":\"{{to_phone}}\",\"type\":\"text\",\"text\":{\"body\":\"{{text_body}}\"}}' },
      { name: 'invoke_mode', label: 'Invoke Mode', type: 'select',
        options: [{ value: 'once_per_batch', label: 'Once Per Batch (Fast)' }, { value: 'per_row', label: 'Per Row' }],
        defaultValue: 'once_per_batch',
        description: 'Use per-row only when you need one message per row; once-per-batch is much faster.' },
      { name: 'preview_url', label: 'Preview URL (text messages)', type: 'toggle', defaultValue: false },
      { name: 'api_version', label: 'Graph API Version', type: 'text', defaultValue: 'v25.0' },
      { name: 'phone_number_id', label: 'Phone Number ID', type: 'text', placeholder: 'Fallback env: BUSINESS_WHATSAPP_PHONE_NUMBER_ID' },
      { name: 'access_token', label: 'Access Token', type: 'password', placeholder: 'Fallback env: BUSINESS_WHATSAPP_ACCESS_TOKEN' },
    ],
  },
]

// ─── FLOW CONTROL ─────────────────────────────────────────────────────────────

const flowNodes: NodeTypeDefinition[] = [
  {
    type: 'condition_node',
    label: 'If / Condition',
    category: 'flow',
    icon: '🔀',
    color: 'var(--app-text-subtle)',
    bgColor: 'rgba(100,116,139,0.1)',
    description: 'Branch pipeline based on a condition',
    inputs: 1,
    outputs: 2,
    tags: ['flow', 'condition', 'branch'],
    configFields: [
      { name: 'field', label: 'Field', type: 'text', required: true },
      { name: 'operator', label: 'Operator', type: 'select',
        options: [
          {value:'equals',label:'Equals'},{value:'not_equals',label:'Not Equals'},
          {value:'greater_than',label:'Greater Than'},{value:'less_than',label:'Less Than'},
        ] },
      { name: 'value', label: 'Value', type: 'text' },
      { name: 'sample_rows_limit', label: 'Preview Rows Limit (0 = unlimited)', type: 'number', defaultValue: 1000,
        description: 'Controls maximum rows used in Condition Studio preview/test. Range: 0..100000.' },
    ],
  },
  {
    type: 'merge_node',
    label: 'Merge',
    category: 'flow',
    icon: '⟨⟩',
    color: 'var(--app-text-subtle)',
    bgColor: 'rgba(100,116,139,0.1)',
    description: 'Merge data from multiple upstream nodes',
    inputs: 2,
    outputs: 1,
    tags: ['flow', 'merge', 'combine'],
    configFields: [
      { name: 'strategy', label: 'Merge Strategy', type: 'select',
        options: [{value:'union',label:'Union (all rows)'},{value:'intersect',label:'Intersect'}],
        defaultValue: 'union' },
    ],
  },
]

// ─── EXPORT ───────────────────────────────────────────────────────────────────

export const ALL_NODE_TYPES: NodeTypeDefinition[] = [
  ...triggerNodes,
  ...sourceNodes,
  ...transformNodes,
  ...destinationNodes,
  ...flowNodes,
]

export const NODE_CATEGORIES = {
  trigger: { label: 'Triggers', color: '#f97316', icon: '▶' },
  source: { label: 'Sources', color: '#3b82f6', icon: '⬇' },
  transform: { label: 'Transforms', color: '#a855f7', icon: '⚙' },
  destination: { label: 'Destinations', color: '#22c55e', icon: '⬆' },
  flow: { label: 'Flow Control', color: 'var(--app-text-subtle)', icon: '⋄' },
}

export const getNodeDef = (type: string): NodeTypeDefinition | undefined =>
  ALL_NODE_TYPES.find(n => n.type === type)
